"""init schema

Revision ID: a4a2c553be8e
Revises: 
Create Date: 2026-02-19 16:21:30.864879
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4a2c553be8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('FACTORY_REGISTERED', 'SHIPMENT_ASSIGNED', 'PACKED', 'IN_TRANSIT', 'PORT_ARRIVED', 'PORT_CLEARED', 'WAREHOUSE_STORED', 'DISPATCHED_TO_SITE', 'SITE_ARRIVED', 'CIVIL_INSTALLATION', 'DC_INSTALLATION', 'AC_INSTALLATION', 'PRE_COMMISSION', 'COLD_COMMISSION', 'HOT_COMMISSION', 'FINAL_ACCEPTANCE', 'ACTIVE', name='bessstage'), nullable=False),
    sa.Column('item_text', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('safety_warning', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('requires_photo', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_templates_stage'), 'checklist_templates', ['stage'], unique=False)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_number', sa.String(length=100), nullable=False),
    sa.Column('capacity_kwh', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_number')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'country_id', name='uq_city_country')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_code', sa.String(length=50), nullable=False),
    sa.Column('origin_country_id', sa.Integer(), nullable=False),
    sa.Column('destination_country_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PACKED', 'IN_TRANSIT', 'ARRIVED', name='shipmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['origin_country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_shipment_code'), 'shipments', ['shipment_code'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_table('engineers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('specialization', sa.Enum('CIVIL', 'DC_ELECTRICAL', 'AC_ELECTRICAL', 'COMMISSIONING', 'GENERAL', name='specialization'), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('max_concurrent_assignments', sa.Integer(), nullable=False),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bess_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('product_model_id', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.Enum('FACTORY_REGISTERED', 'SHIPMENT_ASSIGNED', 'PACKED', 'IN_TRANSIT', 'PORT_ARRIVED', 'PORT_CLEARED', 'WAREHOUSE_STORED', 'DISPATCHED_TO_SITE', 'SITE_ARRIVED', 'CIVIL_INSTALLATION', 'DC_INSTALLATION', 'AC_INSTALLATION', 'PRE_COMMISSION', 'COLD_COMMISSION', 'HOT_COMMISSION', 'FINAL_ACCEPTANCE', 'ACTIVE', name='bessstage'), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('site_address', sa.Text(), nullable=True),
    sa.Column('site_latitude', sa.Float(), nullable=True),
    sa.Column('site_longitude', sa.Float(), nullable=True),
    sa.Column('customer_user_id', sa.Integer(), nullable=True),
    sa.Column('installed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('manufactured_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['installed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_model_id'], ['product_models.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bess_units_serial_number'), 'bess_units', ['serial_number'], unique=True)
    op.create_table('checklist_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bess_unit_id', sa.Integer(), nullable=False),
    sa.Column('checklist_template_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('FACTORY_REGISTERED', 'SHIPMENT_ASSIGNED', 'PACKED', 'IN_TRANSIT', 'PORT_ARRIVED', 'PORT_CLEARED', 'WAREHOUSE_STORED', 'DISPATCHED_TO_SITE', 'SITE_ARRIVED', 'CIVIL_INSTALLATION', 'DC_INSTALLATION', 'AC_INSTALLATION', 'PRE_COMMISSION', 'COLD_COMMISSION', 'HOT_COMMISSION', 'FINAL_ACCEPTANCE', 'ACTIVE', name='bessstage'), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('checked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bess_unit_id'], ['bess_units.id'], ),
    sa.ForeignKeyConstraint(['checked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['checklist_template_id'], ['checklist_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_responses_bess_unit_id'), 'checklist_responses', ['bess_unit_id'], unique=False)
    op.create_table('commissioning_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bess_unit_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('FACTORY_REGISTERED', 'SHIPMENT_ASSIGNED', 'PACKED', 'IN_TRANSIT', 'PORT_ARRIVED', 'PORT_CLEARED', 'WAREHOUSE_STORED', 'DISPATCHED_TO_SITE', 'SITE_ARRIVED', 'CIVIL_INSTALLATION', 'DC_INSTALLATION', 'AC_INSTALLATION', 'PRE_COMMISSION', 'COLD_COMMISSION', 'HOT_COMMISSION', 'FINAL_ACCEPTANCE', 'ACTIVE', name='bessstage'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bess_unit_id'], ['bess_units.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissioning_records_bess_unit_id'), 'commissioning_records', ['bess_unit_id'], unique=False)
    op.create_table('shipment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('bess_unit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bess_unit_id'], ['bess_units.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'bess_unit_id', name='uq_shipment_item')
    )
    op.create_table('site_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bess_unit_id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_stage', sa.Enum('FACTORY_REGISTERED', 'SHIPMENT_ASSIGNED', 'PACKED', 'IN_TRANSIT', 'PORT_ARRIVED', 'PORT_CLEARED', 'WAREHOUSE_STORED', 'DISPATCHED_TO_SITE', 'SITE_ARRIVED', 'CIVIL_INSTALLATION', 'DC_INSTALLATION', 'AC_INSTALLATION', 'PRE_COMMISSION', 'COLD_COMMISSION', 'HOT_COMMISSION', 'FINAL_ACCEPTANCE', 'ACTIVE', name='bessstage'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'REASSIGNED', 'DECLINED', name='assignmentstatus'), nullable=False),
    sa.Column('assigned_by', sa.String(length=10), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bess_unit_id'], ['bess_units.id'], ),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_assignments_bess_unit_id'), 'site_assignments', ['bess_unit_id'], unique=False)
    op.create_table('stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bess_unit_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.Enum('FACTORY_REGISTERED', 'SHIPMENT_ASSIGNED', 'PACKED', 'IN_TRANSIT', 'PORT_ARRIVED', 'PORT_CLEARED', 'WAREHOUSE_STORED', 'DISPATCHED_TO_SITE', 'SITE_ARRIVED', 'CIVIL_INSTALLATION', 'DC_INSTALLATION', 'AC_INSTALLATION', 'PRE_COMMISSION', 'COLD_COMMISSION', 'HOT_COMMISSION', 'FINAL_ACCEPTANCE', 'ACTIVE', name='bessstage'), nullable=False),
    sa.Column('to_stage', sa.Enum('FACTORY_REGISTERED', 'SHIPMENT_ASSIGNED', 'PACKED', 'IN_TRANSIT', 'PORT_ARRIVED', 'PORT_CLEARED', 'WAREHOUSE_STORED', 'DISPATCHED_TO_SITE', 'SITE_ARRIVED', 'CIVIL_INSTALLATION', 'DC_INSTALLATION', 'AC_INSTALLATION', 'PRE_COMMISSION', 'COLD_COMMISSION', 'HOT_COMMISSION', 'FINAL_ACCEPTANCE', 'ACTIVE', name='bessstage'), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bess_unit_id'], ['bess_units.id'], ),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_history_bess_unit_id'), 'stage_history', ['bess_unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_history_bess_unit_id'), table_name='stage_history')
    op.drop_table('stage_history')
    op.drop_index(op.f('ix_site_assignments_bess_unit_id'), table_name='site_assignments')
    op.drop_table('site_assignments')
    op.drop_table('shipment_items')
    op.drop_index(op.f('ix_commissioning_records_bess_unit_id'), table_name='commissioning_records')
    op.drop_table('commissioning_records')
    op.drop_index(op.f('ix_checklist_responses_bess_unit_id'), table_name='checklist_responses')
    op.drop_table('checklist_responses')
    op.drop_index(op.f('ix_bess_units_serial_number'), table_name='bess_units')
    op.drop_table('bess_units')
    op.drop_table('warehouses')
    op.drop_table('engineers')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_shipments_shipment_code'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_table('role_permissions')
    op.drop_table('cities')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('product_models')
    op.drop_table('permissions')
    op.drop_table('countries')
    op.drop_index(op.f('ix_checklist_templates_stage'), table_name='checklist_templates')
    op.drop_table('checklist_templates')
    # ### end Alembic commands ###
