from __future__ import annotations

from enum import Enum


class BESSStage(str, Enum):
    FACTORY_REGISTERED = "FACTORY_REGISTERED"
    SHIPMENT_ASSIGNED = "SHIPMENT_ASSIGNED"
    PACKED = "PACKED"
    IN_TRANSIT = "IN_TRANSIT"
    PORT_ARRIVED = "PORT_ARRIVED"
    PORT_CLEARED = "PORT_CLEARED"
    WAREHOUSE_STORED = "WAREHOUSE_STORED"
    DISPATCHED_TO_SITE = "DISPATCHED_TO_SITE"
    SITE_ARRIVED = "SITE_ARRIVED"
    CIVIL_INSTALLATION = "CIVIL_INSTALLATION"
    DC_INSTALLATION = "DC_INSTALLATION"
    AC_INSTALLATION = "AC_INSTALLATION"
    PRE_COMMISSION = "PRE_COMMISSION"
    COLD_COMMISSION = "COLD_COMMISSION"
    HOT_COMMISSION = "HOT_COMMISSION"
    FINAL_ACCEPTANCE = "FINAL_ACCEPTANCE"
    ACTIVE = "ACTIVE"


STAGE_TRANSITIONS: dict[BESSStage, BESSStage] = {
    BESSStage.FACTORY_REGISTERED: BESSStage.SHIPMENT_ASSIGNED,
    BESSStage.SHIPMENT_ASSIGNED: BESSStage.PACKED,
    BESSStage.PACKED: BESSStage.IN_TRANSIT,
    BESSStage.IN_TRANSIT: BESSStage.PORT_ARRIVED,
    BESSStage.PORT_ARRIVED: BESSStage.PORT_CLEARED,
    BESSStage.PORT_CLEARED: BESSStage.WAREHOUSE_STORED,
    BESSStage.WAREHOUSE_STORED: BESSStage.DISPATCHED_TO_SITE,
    BESSStage.DISPATCHED_TO_SITE: BESSStage.SITE_ARRIVED,
    BESSStage.SITE_ARRIVED: BESSStage.CIVIL_INSTALLATION,
    BESSStage.CIVIL_INSTALLATION: BESSStage.DC_INSTALLATION,
    BESSStage.DC_INSTALLATION: BESSStage.AC_INSTALLATION,
    BESSStage.AC_INSTALLATION: BESSStage.PRE_COMMISSION,
    BESSStage.PRE_COMMISSION: BESSStage.COLD_COMMISSION,
    BESSStage.COLD_COMMISSION: BESSStage.HOT_COMMISSION,
    BESSStage.HOT_COMMISSION: BESSStage.FINAL_ACCEPTANCE,
    BESSStage.FINAL_ACCEPTANCE: BESSStage.ACTIVE,
}


SITE_STAGES = {
    BESSStage.SITE_ARRIVED,
    BESSStage.CIVIL_INSTALLATION,
    BESSStage.DC_INSTALLATION,
    BESSStage.AC_INSTALLATION,
    BESSStage.PRE_COMMISSION,
    BESSStage.COLD_COMMISSION,
    BESSStage.HOT_COMMISSION,
    BESSStage.FINAL_ACCEPTANCE,
}


STAGE_TO_SPECIALIZATION: dict[BESSStage, str] = {
    BESSStage.CIVIL_INSTALLATION: "CIVIL",
    BESSStage.DC_INSTALLATION: "DC_ELECTRICAL",
    BESSStage.AC_INSTALLATION: "AC_ELECTRICAL",
    BESSStage.PRE_COMMISSION: "COMMISSIONING",
    BESSStage.COLD_COMMISSION: "COMMISSIONING",
    BESSStage.HOT_COMMISSION: "COMMISSIONING",
    BESSStage.SITE_ARRIVED: "GENERAL",
    BESSStage.FINAL_ACCEPTANCE: "GENERAL",
}


class AssignmentStatus(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    REASSIGNED = "REASSIGNED"
    DECLINED = "DECLINED"


class Specialization(str, Enum):
    CIVIL = "CIVIL"
    DC_ELECTRICAL = "DC_ELECTRICAL"
    AC_ELECTRICAL = "AC_ELECTRICAL"
    COMMISSIONING = "COMMISSIONING"
    GENERAL = "GENERAL"


class ShipmentStatus(str, Enum):
    CREATED = "CREATED"
    PACKED = "PACKED"
    IN_TRANSIT = "IN_TRANSIT"
    ARRIVED = "ARRIVED"
